name: uniconnect
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  google_fonts: ^8.0.1
  go_router: ^17.1.0
  flutter_riverpod: ^3.2.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  http: ^1.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  freezed: ^3.2.3
  json_serializable: ^6.13.0
  mocktail: ^1.0.4
flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
